services:
  postgres:
    image: postgres:16
    container_name: gocommerce_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_gocommerce:/var/lib/postgresql/data
    networks:
      - gocommerce_network

volumes:
  postgres_data_gocommerce:

networks:
  gocommerce_network:
